Change Log
==========

https://github.com/eraserhd/rep/compare/v0.2.0...HEAD[Unreleased]
-----------------------------------------------------------------

https://github.com/eraserhd/rep/compare/v0.1.2...v0.2.0[v0.2.0]
---------------------------------------------------------------

* Completely rewrite in C for portability.

=== Added

* `--port` accept `@FNAME@RELATIVE` to find a port file in a parent.
* Finding `.nrepl-port` in the current directory or a parent is now the
  default behavior.
* List-valued replies can now be formatted using `%{KEY,SUBFORMAT}`
  syntax, and `%.` in SUBFORMAT refers to the current value.
* `--verbose` option for debugging.

https://github.com/eraserhd/rep/compare/v0.1.1...v0.1.2[v0.1.2]
----------------------------------------------------------------

=== Added

* Add `--op` to specify an operation other than "eval".
* Add `--print` option to specify which keys in response messages to print
  and how.
* Add `--send` to send additional keys in request messages.

=== Kakoune

* `,eR` replaces selection with its evaluated result.

https://github.com/eraserhd/rep/compare/v0.1.0...v0.1.1[v0.1.1] - 2019-01-08
--------------------------------------------------------------------------

=== Added

* Add `-n`, `--namespace` option to specify the namespace of evaluated code.
* Add `-l`, `--line` option to specify the file, line number, and column of
  evaluated code.
* Now releasing Linux binaries (thanks Circle CI!)
* Documentation updatings, including an example of how an editor might invoke
  `rep`

=== Kakoune

* Evaluates code in the namespace of the file if it can detect an `ns` form
  at the top. 
* Sends file name and position when evaluating code.

0.1.0 - 2018-11-30
------------------

=== Added

* First release with basic features (able to evaluate code and print
  results).
