# generated by clj2nix-1.0.4
{ pkgs ? import <nixpkgs> {} }:
  
  let repos = [
        "https://repo.clojars.org/"
        "https://repo1.maven.org/"
        "http://central.maven.org/maven2/"
        "http://oss.sonatype.org/content/repositories/releases/"
        "http://oss.sonatype.org/content/repositories/public/"
        "http://repo.typesafe.com/typesafe/releases/"
      ];

  in rec {
      makePaths = {extraClasspaths ? []}: (builtins.map (dep: if builtins.hasAttr "jar" dep.path then dep.path.jar else dep.path) packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}: builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});

      packages = [
  {
    name = "org.clojure/tools.cli";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.cli";
      groupId = "org.clojure";
      sha512 = "28992520462503c069f853c1d5a47e67159a09499c41db74d97de79cc9d3eaaa7aee12905ea4cc9e9b6672595378966b874b6b2b28354d246fd1540a0b74ea73";
      version = "0.4.1";
    };
  }

  {
    name = "nrepl/nrepl";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "nrepl";
      groupId = "nrepl";
      sha512 = "c763d0b37b54948b55635577aff245908996f88e29e286e2907086fc81fca7892c72df1105e4284859f6d068eeb510a105d7cc1289a3f0bd1b6d526f78b09f51";
      version = "0.5.3";
    };
  }

  {
    name = "org.clojure/core.specs.alpha";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "348c0ea0911bc0dcb08655e61b97ba040649b4b46c32a62aa84d0c29c245a8af5c16d44a4fa5455d6ab076f4bb5bbbe1ad3064a7befe583f13aeb9e32a169bf4";
      version = "0.2.44";
    };
  }

  {
    name = "nrepl/bencode";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "bencode";
      groupId = "nrepl";
      sha512 = "b3b93809354d45953329b67fb79795cccfb995bf19985f71adba26376ecb19810fdfbc75f9ad31f00a42dba161e6746a6b933dffd7346971771670e6f6903442";
      version = "1.0.0";
    };
  }

  ];
  }
  