= rep

https://github.com/eraserhd/rep

A single-shot nREPL client designed for shell invocation.

This connects to a running nREPL server (like kind started with `lein repl`,
for example), sends some code to be evaluated, and prints the results and
output.

 $ rep '(clojure.tools.namespace.repl/refresh)'
 :reloading ()
 :ok

Unlike other nREPL clients, `rep` does not try to maintain a persistent
connection, meaning that thread-local variables and bindings like `*e` and
`*1` will not persist across invocations of `rep`.  Perhaps there are
other limitations because of this?

== Installation

Download the latest MacOS binaries from the GitHub releases tab above.

== Building with Graal

This is a somewhat graaling process right now, so bear with me.

First, leiningen wants different versions of nREPL, and we've needed to hack
up nREPL's transport.clj, so we need to use leiningen 2.8.1 exactly, so I've
copied that to `./lein`.

At the moment, Graal doesn't deal well with the way Clojure generates bytecode
from its 'locking' macro, so to build bytecode that Graal can handle, we need
to apply https://dev.clojure.org/jira/secure/attachment/18767/clj-1472-3.patch[this patch].
This issue is being tracked
https://dev.clojure.org/jira/browse/CLJ-1472[here] and
https://github.com/oracle/graal/issues/861[here].

After applying the patch and invoking 'mvn install' for Clojure, you will need
to clone, build, and install 'spec.alpha' with that version of Clojure.

When that's done, you can update the versions of Clojure and spec.alpha
referenced in the project.clj to match the snapshots you've just locally
installed.

Assuming you've already installed Graal VM and put it in the path, you should
then be able to build the image:

  $ ./lein native-image

You will find it in 'target/default+uberconf/rep'.

== Usage, Options, and Examples

See https://github.com/eraserhd/rep/blob/develop/rep.1.adoc[the rep manpage].

== Using with Kakoune

The `rc/` folder contains scripts which add a `,e` user mode to Kakoune.  To
link this to Kakoiune's autoload directory, do the following:

  $ make install

`rep` must be in the path for the plugin to work.

== License

Copyright © 2018 Jason M. Felice, except for included code written
by other people.

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.
