= REP(1)
:doctype: manpage


== NAME
rep - a single-shot nREPL client

== SYNOPSIS
*rep* ['OPTIONS'] 'EXPR' ...

== DESCRIPTION

`rep` connects to a running nREPL server, sends a bit of code, and prints
the result.

Unlike other nREPL clients, `rep` does not try to maintain a persistent
connection, meaning that thread-local variables and bindings like `*e` and
`*1` will not persist across invocations of `rep`.

== OPTIONS
*--*::
    End of options.  Useful to send code which starts with a dash.

*-h, --help*::
    Show a summary of help options.

*-l, --line*='[FILE:]LINE[:COLUMN]'::
    Specify the FILE, LINE number, and COLUMN of the code being evaluated.
    This is used by for compile errors, exceptions, and metadata on evaluated
    symbols, so specifying this will improve your error messages.

    LINE must be supplied if COLUMN is supplied, but all other combinations
    are allowed.

*-n, --namespace*=NS::
    Evaluate code in NS.  'ns' forms themselves should be evaluated in 'user'
    in case they don't already exist.  'user' is the default.

*--no-print*=KEY::
    Do not print KEY.  Used to suppress output for one of the keys printed by
    default, `out`, `err`, or `value`.  (See *--print*.)

*--op*=OP::
    Specify an nREPL operation.  The default is "eval".

*-p, --port*='@FILE|[HOST:]PORT'::
    Specify the nREPL 'PORT' and possibly 'HOST'.  If 'FILE' is given, the
    host and port are read from a file.  If 'HOST' is not given, 'localhost'
    is assumed.  The default is '@.nrepl-port', which will find the running
    nREPL if it was invoked by Leiningen.

*--print*=KEY[,FD[,FORMAT]]::
    Print KEY in response messages to FD, using FORMAT.  If FORMAT has a `%s`
    in it, it is replaced with the value of KEY.  If FD is omitted, 1 (stdout)
    is used.  If FORMAT is omitted, `%s` is used.  By default, `out` is
    printed to stdout, `err` is printed to stderr, and `value` is printed to
    stdout with a trailing newline.  (See also *--no-print*.)

*--send*=KEY,TYPE,VALUE::
    Send KEY in request message with VALUE.  TYPE can be either `string` or
    `integer`.

== EXAMPLES
`rep '(+ 2 2)'`::
    Evaluate a simple expression in the running nREPL server and print its
    result.

`rep '(clojure.tools.namespace.repl/refresh)'`::
    Cause the running nREPL to reload any files which were changed.

`rep -l src/foo/myfile.clj:26:7 -n foo.myfile '(+ 26 99)'`::
    This is how an editor might invoke `rep` when the user requests evaluation
    of the form under the cursor.  In addition to extracting the form under
    the cursor, the editor will need some mechanism to extract the file's
    namespace for the `-n` option.  `rep` will print `125`, which the editor
    can display in its echo area, log, scratch buffer, or what not.

`rep --op=list-sessions --print=sessions`::
    Print the list of the active nREPL sessions.

`rep --op=slurp --send=url,string,http://eraserhead.net/ --print=body`::
    Use CIDER's "slurp" operation to retrieve http://eraserhead.net/.

== EXIT STATUS
*0*::
    Success

*1*::
    One of the expressions given threw an exception.

*2*::
    An error occurred while parsing options.
