= REP(1)
:doctype: manpage


== NAME
rep - a single-shot nREPL client

== SYNOPSIS
*rep* ['OPTIONS'] 'EXPR' ...

== OPTIONS
*--*::
    End of options.  Useful to send code which starts with a dash.

*-h, --help*::
    Show a summary of help options.

*-l, --line*='[FILE:]LINE[:COLUMN]'::
    Specify the FILE, LINE number, and COLUMN of the code being evaluated.
    This is used by for compile errors, exceptions, and metadata on evaluated
    symbols, so specifying this will improve your error messages.

    LINE must be supplied if COLUMN is supplied, but all other combinations
    are allowed.

*-n, --namespace*=NS::
    Evaluate code in NS.  'ns' forms themselves should be evaluated in 'user'
    in case they don't already exist.  'user' is the default.

*-p, --port*='@FILE|[HOST:]PORT'::
    Specify the nREPL 'PORT' and possibly 'HOST'.  If 'FILE' is given, the
    host and port are read from a file.  If 'HOST' is not given, 'localhost'
    is assumed.  The default is '@.nrepl-port', which will find the running
    nREPL if it was invoked by Leiningen.

== EXAMPLES
`rep '(+ 2 2)'`::
    Evaluate a simple expression in the running nREPL server and print its
    result.

== EXIT STATUS
*0*::
    Success

*1*::
    One of the expressions given threw an exception.

*2*::
    An error occurred while parsing options.
