# generated by clj2nix-1.0.5
{ pkgs ? import <nixpkgs> {} }:

  let repos = [
        "https://repo1.maven.org/maven2/"
        "https://repo.clojars.org/"
        "http://oss.sonatype.org/content/repositories/releases/"
        "http://oss.sonatype.org/content/repositories/public/"
        "http://repo.typesafe.com/typesafe/releases/"
      ];

  in rec {
      makePaths = {extraClasspaths ? []}: (builtins.map (dep: if builtins.hasAttr "jar" dep.path then dep.path.jar else dep.path) packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}: builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});

      packages = [
  {
    name = "org.clojure/clojure";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "7fdcc6fe280c44966cbe38b2758cacb3eadfade07eca9ce0a50bbf71129a6ce0e7b1959067f6b7f47500b30bdf7a68891e18600d5b1c2afc7288f0bbb330ec2f";
      version = "1.9.0";
    };
  }

  {
    name = "joda-time/joda-time";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "joda-time";
      groupId = "joda-time";
      sha512 = "3a6749ecd71ee8d5781821c36d77850a810e72ee33757ec4ee9e3d424676dced7eeb955a432f45edb3694dc14dbe1ee4c608545d6a445b29b86979a7c9829384";
      version = "2.9.9";
    };
  }

  {
    name = "commons-codec/commons-codec";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "commons-codec";
      groupId = "commons-codec";
      sha512 = "d9586162b257386b5871e7e9ae255a38014a9efaeef5148de5e40a3b0200364dad8516bddd554352aa2e5337bec2cc11df88c76c4fdde96a40f3421aa60650d7";
      version = "1.11";
    };
  }

  {
    name = "org.clojure/core.specs.alpha";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "b4f5eee01da39914e6024dd529d1f72952d5a9dae65e1e41bf386b1e86a004a0d197b5be95aa70e7e8d6438c92b7fa8fc0c5039f2013e97c0b91c22d86fb7968";
      version = "0.1.24";
    };
  }

  {
    name = "marick/suchwow";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "suchwow";
      groupId = "marick";
      sha512 = "1847d7a3f7e6309ec76f1cfd918841ec123129c9e4828264290da0a534c6b22c173357ea890e153e59e2e5aa4c876b9f7269ddab09ad4dbab483f6275fdcc8e3";
      version = "6.0.2";
    };
  }

  {
    name = "colorize/colorize";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "colorize";
      groupId = "colorize";
      sha512 = "bb754a1e85da2a261b6b0ee226b5e52d96fb89fda4c245487b91e8f2d98dedf46e2ca255522913e4701277e761d818f40e446fca01fcb96486e79789a83c3d17";
      version = "0.1.1";
    };
  }

  {
    name = "org.clojure/spec.alpha";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "b8fc40ed9bc52b545e699ed188dd61bfd144ee67f0c70364b8f2715e9f1fea608d3721db7f618f6ef4bc3056e3c2984c626080486ca710f3595dda8ba23730ac";
      version = "0.1.143";
    };
  }

  {
    name = "org.clojure/tools.cli";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.cli";
      groupId = "org.clojure";
      sha512 = "28992520462503c069f853c1d5a47e67159a09499c41db74d97de79cc9d3eaaa7aee12905ea4cc9e9b6672595378966b874b6b2b28354d246fd1540a0b74ea73";
      version = "0.4.1";
    };
  }

  {
    name = "mvxcvi/puget";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "puget";
      groupId = "mvxcvi";
      sha512 = "d93ec2165f24de69927a68d7e4a58b3b0a5f510a4384434823bce65990fc4e241d9d51d6b72d3e36509d8cc69dab9c68656aa1ff2db7d131261cbe0643d1c16b";
      version = "1.0.2";
    };
  }

  {
    name = "org.clojure/tools.macro";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.macro";
      groupId = "org.clojure";
      sha512 = "65ce5e29379620ac458274c53cd9926e4b764fcaebb1a2b3bc8aef86bbe10c79e654b028bc4328905d2495a680fa90f5002cf5c47885f6449fad43a04a594b26";
      version = "0.1.5";
    };
  }

  {
    name = "io.aviso/pretty";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "pretty";
      groupId = "io.aviso";
      sha512 = "4db5a38fda3d32db0d47c13e7b321f393764d0200e7a5d61ee7ad89bf9bef172d80f98e99d9e8df7416fd73a2a40d8418543758e754285b8f1670de782d11d64";
      version = "0.1.35";
    };
  }

  {
    name = "slingshot/slingshot";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "slingshot";
      groupId = "slingshot";
      sha512 = "ff2b2a27b441d230261c7f3ec8c38aa551865e05ab6438a74bd12bfcbc5f6bdc88199d42aaf5932b47df84f3d2700c8f514b9f4e9b5da28d29da7ff6b09a7fb5";
      version = "0.12.2";
    };
  }

  {
    name = "org.clojure/tools.namespace";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.namespace";
      groupId = "org.clojure";
      sha512 = "5b42402985b6147050204539be75159f471d234c97d172e1c56b962de9ed2737dcb6987f32221309cacb963d1e15c54a27038ff918ff11e5c79e3341634f99ba";
      version = "0.3.0-alpha4";
    };
  }

  {
    name = "fipp/fipp";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "fipp";
      groupId = "fipp";
      sha512 = "6d8484301d97e2a05867b13178c11cf11891117023aea7c24aa7142b6513d6d4dd7190850082fa429590ac2b0c631dad7d448b3bfdc99f0a50b439dc9309e7c7";
      version = "0.6.13";
    };
  }

  {
    name = "clj-time/clj-time";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-time";
      groupId = "clj-time";
      sha512 = "0922a685db72947f2e4275e6ffb9b1475ffa3362af354ac5b4f8dc07c9f27fafe178ce2da50755d05f667e38ae18e1b031417dbaf01b2db899e8b689ce61dbcb";
      version = "0.14.4";
    };
  }

  {
    name = "mvxcvi/arrangement";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "arrangement";
      groupId = "mvxcvi";
      sha512 = "1b69aa23a86d96d4aadde5f09c8b0e847cbbab6f6762b01499e1be63aa34f655d5427edfeea0d21b91a5a35fee447c5dd72a792ebea1dcb9cdc7906866560d34";
      version = "1.1.1";
    };
  }

  {
    name = "clj-tuple/clj-tuple";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-tuple";
      groupId = "clj-tuple";
      sha512 = "dd626944d0aba679a21b164ed0c77ea84449359361496cba810f83b9fdeab751e5889963888098ce4bf8afa112dbda0a46ed60348a9c01ad36a2e255deb7ab6d";
      version = "0.2.2";
    };
  }

  {
    name = "flare/flare";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "flare";
      groupId = "flare";
      sha512 = "4e46d13382540e29d9dc1ccc5ecdab4a5cfe56f6524a1cb319f1a53517adb3c45a52a4b59b9ff54ce2496619ca2362c9e94a07e36b3fdddcfeb1922070367915";
      version = "0.2.9";
    };
  }

  {
    name = "riddley/riddley";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "riddley";
      groupId = "riddley";
      sha512 = "b478ecba9d1ab9d38c84a42354586fcece763000907b40c97bc43c0f16dc560b0860144efe410193cb3b7cb0149fbc1724fdd737cc3ba53de23618f5b30e6f9f";
      version = "0.1.12";
    };
  }

  {
    name = "org.clojure/core.unify";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "core.unify";
      groupId = "org.clojure";
      sha512 = "2613d5b17cdd6bfbfd62db1ec5e9f0dce1034bc40b3c91f88088646542edc8836722276b0b7d47c5aefacfb123aee1a74a6a3cbe43859f1ecc9099f1435cc29d";
      version = "0.5.7";
    };
  }

  {
    name = "org.clojure/java.classpath";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "java.classpath";
      groupId = "org.clojure";
      sha512 = "e583db27471744d51ec2a5a64de7bfb6d438de33ebc4318cb168e0e58b38d435f4ce14a82bf4783700156ee82ab7ae6690ea166e809c94c323cb5a2f8918fe8c";
      version = "0.2.3";
    };
  }

  {
    name = "environ/environ";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "environ";
      groupId = "environ";
      sha512 = "60b028d337abbadb8d9c50c8af00c269a7d84ea656a0119cd170d3f6b93067020ec3104579c92c5e3c7fd96b363ecf37d8c43a69445bf6d1b431cb603ac3d09d";
      version = "1.1.0";
    };
  }

  {
    name = "org.clojure/core.rrb-vector";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "core.rrb-vector";
      groupId = "org.clojure";
      sha512 = "5f737bf3ca3acf567b2b5c14b5761c8c38e94e1f6168f8cba9f46d2ae41334ae3d68d2c00663827a6214094d96b9767f6803f66ab44b0012c6f2e3c2997b1796";
      version = "0.0.13";
    };
  }

  {
    name = "org.clojure/math.combinatorics";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "math.combinatorics";
      groupId = "org.clojure";
      sha512 = "ac9e614c2be39f0218cc6ff58b797bed773a163e0177423d3b57c45f8e71f899401ffeef3814c27546dcbad511202651a12d35cf9183991e238fb3e974854985";
      version = "0.1.4";
    };
  }

  {
    name = "org.clojure/tools.reader";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "tools.reader";
      groupId = "org.clojure";
      sha512 = "ac36ba633ea9a2f4309b72fb5fd4dbe2f88870d9766ac57c45ab3a4997b73487056def3bf2aa996e01f07c91015147e480bc6d935916d9c13d8018125c0df186";
      version = "0.10.0";
    };
  }

  {
    name = "org.tcrawley/dynapath";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "dynapath";
      groupId = "org.tcrawley";
      sha512 = "1b0caf390515212e6b151d6c227b1a62e430e682b6c811736edba3cc918344053e35c092e12afd523198ed6244018450931776f8388e61a593f266476b6db19e";
      version = "1.0.0";
    };
  }

  {
    name = "potemkin/potemkin";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "potemkin";
      groupId = "potemkin";
      sha512 = "85ae548671efff81399dace661f8e4ce5150377475d31701a22b4f3c2bd3b615518fa938fffe3249c945ad1bcd7295243967429144bbce57a22e2303c7081875";
      version = "0.4.4";
    };
  }

  {
    name = "nrepl/nrepl";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "nrepl";
      groupId = "nrepl";
      sha512 = "c763d0b37b54948b55635577aff245908996f88e29e286e2907086fc81fca7892c72df1105e4284859f6d068eeb510a105d7cc1289a3f0bd1b6d526f78b09f51";
      version = "0.5.3";
    };
  }

  {
    name = "com.rpl/specter";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "specter";
      groupId = "com.rpl";
      sha512 = "9037cbe78efbdc18eabc8cd3919fa7fca5312b6fe3efccd146d7b0becbd281d8bfc5b4d6fb25abebdf603f88708f8ab9ebddc57ac93b642fc45083d30cbd8258";
      version = "1.0.5";
    };
  }

  {
    name = "org.clojure/test.check";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "test.check";
      groupId = "org.clojure";
      sha512 = "bf57571a9d31d50cf15b38134f4d7c34d03eb458bc62b30c7a1dbf233e300c67f1fda6673dbd1584a0497cf8875f972e6697e7f13d0c3e70e4254697b1b75cc6";
      version = "0.10.0-alpha3";
    };
  }

  {
    name = "nrepl/bencode";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "bencode";
      groupId = "nrepl";
      sha512 = "b3b93809354d45953329b67fb79795cccfb995bf19985f71adba26376ecb19810fdfbc75f9ad31f00a42dba161e6746a6b933dffd7346971771670e6f6903442";
      version = "1.0.0";
    };
  }

  {
    name = "midje";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "midje";
      groupId = "midje";
      sha512 = "1715271f2b125335eb67c5d5cab7eeade3fdb7f1b58eb03de9bf5d127a0f07a44c1af297d19cb4f6dd17b8d59c6eac1f0e983429dc07ca2485f964465c347e7d";
      version = "1.9.4";
    };
  }

  {
    name = "org.clojars.brenton/google-diff-match-patch";
    path = pkgs.fetchMavenArtifact {
      inherit repos;
      artifactId = "google-diff-match-patch";
      groupId = "org.clojars.brenton";
      sha512 = "896083e1a0c9353122c01c974f86159b389c8cafd1aed73154e494c77a4edc19952dbb56ee4b8dbbd2a2fa6e6fb1495d93338c0d3c12d4a3507864bba8f11d03";
      version = "0.1";
    };
  }

  ];
  }
  